
language: elixir
elixir:
  - 1.3
otp_release:
  - 19.0
sudo: false
addons:
  postgresql: '9.5' # Use postgres 9.5
before_script:
# Create the test database
- psql -c 'create database peepchat_test;' -U postgres